version: "3.9"
services:
  app:
    build: .
    ports: 
      - "5000:5000"
    volume: 
      - /media/upload:/app/upload
    env_file: 
      - .env
  web: 
    build: ansible/roles/configure_web_server/files
    ports:
      - "80:80"