---
# tasks file for configure_zabbix
- name: install git
  yum: name=git state=installed

- name: rm repo
  shell: "rm -rf zabbix-docker"

- name: clone zabbix repo with docker-compose
  git:
    repo: 'https://github.com/zabbix/zabbix-docker'
    dest: 'zabbix-docker'

- name: Move foo to bar
  command: mv zabbix-docker/docker-compose_v3_alpine_mysql_latest.yaml  zabbix-docker/docker-compose.yml

- name: run the service defined in my_project's docker-compose.yml
  docker_compose:
    project_src: zabbix-docker
    state: present