---
- name: add epel-release
  yum: name=epel-release state=installed

- name: install nginx
  yum: name=nginx state=installed

- name: create folder for flask app
  file:
    path: /var/www/flask_app
    state: directory

- name: Generate index.html
  template: src=index.j2 dest=/var/www/flask_app/index.html
  notify: Restart nginx

- name: Generate nginx.conf
  template: src=nginx.j2 dest=/etc/nginx/nginx.conf
  notify: Restart nginx  

- name: started nginx and enabled start on boot
  service: name=nginx state=started enabled=yes

- name: add firewalld rule
  firewalld: 
    zone: public
    service: http
    permanent: true
    state: enabled
  notify: Restart firewalld

- name: add firewalld rule
  firewalld:
    zone: public
    service: https
    permanent: true
    state: enabled
  notify: Restart firewalld
    
