version: "3"
services:
  tcs:
    image: jetbrains/teamcity-server
    container_name: teamcity-server
    ports:
      - "8111:8111"
    volumes:
      - /data/teamcity_server/datadir:/data/teamcity_server/datadir
      - /opt/teamcity/logs:/opt/teamcity/logs
  tca:
    image: jetbrains/teamcity-agent:2020.2-linux-sudo
    depends_on:
      - tcs
    container_name: teamcity-agent
    environment:
      SERVER_URL: "http://tcs:8111/"
      DOCKER_IN_DOCKER: start
    volumes:
      - /data/teamcity_agent/conf:/data/teamcity_agent/conf
    privileged: true