version: "3"
services:
  tcs:
    image: jetbrains/teamcity-server
    container_name: teamcity-server
    ports:
      - "8111:8111"
    volumes:
      - /data/teamcity_server/datadir:/data/teamcity_server/datadir
      - /opt/teamcity/logs:/opt/teamcity/logs
  tca:
    image: jetbrains/teamcity-agent
    depends_on:
      - tcs
    container_name: teamcity-agent
    environment:
      SERVER_URL: "http://tcs:8111/"
      DOCKER_IN_DOCKER: start
    volumes:
      - /data/teamcity_agent/conf:/data/teamcity_agent/conf
      # - /data/lib/docker:var/lib/docker
    privileged: true
    # environment: 
      
# docker run -it -e SERVER_URL="<url to TeamCity server>"  \
#     -u 0 \
#     -v <path to agent config folder>:/data/teamcity_agent/conf \
#     -v /var/run/docker.sock:/var/run/docker.sock  \
#     -v /opt/buildagent/work:/opt/buildagent/work \
#     -v /opt/buildagent/temp:/opt/buildagent/temp \
#     -v /opt/buildagent/tools:/opt/buildagent/tools \
#     -v /opt/buildagent/plugins:/opt/buildagent/plugins \
#     -v /opt/buildagent/system:/opt/buildagent/system \
#     jetbrains/teamcity-agent