---
- name: create build directory
  file:
    path: /data/teamcity_agent/conf
    state: directory
    owner: root
    group: root
    mode: '0777'

- name: copy docker-compose.yml
  copy:
    src: docker-compose.yml
    dest: /data
    owner: root
    group: root
    mode: '0644'

- name: install docker-compose pip
  pip: name=docker-compose

- name: run the service defined in my_project's docker-compose.yml
  docker_compose:
    project_src: /data
    state: present